blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation & Getting Started
    url: https://github.com/OutdatedGuy/cached_video_player_plus/blob/main/README.md
    about: Check out our comprehensive documentation and getting started guide
  - name: 💬 Community Discussion
    url: https://github.com/OutdatedGuy/cached_video_player_plus/discussions
    about: Ask questions, share ideas, and discuss with the community
  - name: 🆘 Need Help?
    url: https://stackoverflow.com/questions/tagged/flutter+video-player
    about: Get help from the Flutter community on Stack Overflow
